### ISSUE TITLE
run error in mac ox

### ISSUE THREAD

**Issue by tqyq** [rockyzhengwu/FoolNLTK#6]
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/altman/IdeaProjects/gopath/src/labs/fool_test/test.py
/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
starting load model 
Traceback (most recent call last):
  File "/Users/altman/IdeaProjects/gopath/src/labs/fool_test/test.py", line 4, in <module>
    print(fool.cut(text))
  File "/usr/local/lib/python3.6/site-packages/fool/__init__.py", line 36, in cut
    _check_model()
  File "/usr/local/lib/python3.6/site-packages/fool/__init__.py", line 26, in _check_model
    LEXICAL_ANALYSER.load_model()
  File "/usr/local/lib/python3.6/site-packages/fool/lexical.py", line 75, in load_model
    self.map = DataMap(os.path.join(data_path, "maps.pkl"))
  File "/usr/local/lib/python3.6/site-packages/fool/lexical.py", line 20, in __init__
    self._load(path)
  File "/usr/local/lib/python3.6/site-packages/fool/lexical.py", line 26, in _load
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/fool/maps.pkl'

Process finished with exit code 1

**Comment by rockyzhengwu** [comment]
I load model from ```sys.prefix```  

you can copy the model file to /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/fool/

I will fix this next version !

thanks !!

**Comment by liu-nlper** [comment]
same error on ubuntu, how to solve?
FileNotFoundError: [Errno 2] No such file or directory: '/usr/fool/maps.pkl'

**Comment by rockyzhengwu** [comment]
@liu-nlper 
you can  copy  ```fool ``` from ```/usr/local``` to ```/usr/ ```

**Comment by liu-nlper** [comment]
@rockyzhengwu 好了，很好的工具，建议把文档写的全点，给出训练语料来源，词性映射表之类的；还有增加一些和其它工具的在开源语料上的对比实验，包括分词性能和分词速度。

**Comment by rockyzhengwu** [comment]
@liu-nlper 谢谢建议，正在努力中

**Comment by kumiko-oreyome** [comment]
What is the dataset for training named entity recognition model?
Is the dataset available(open)? 
Thank you!!

**Comment by xidiandb** [comment]
怎么解决的
