### ISSUE TITLE
在引入模块时出错。Error raised when import fool module.

### ISSUE THREAD

**Issue by happypycode** [rockyzhengwu/FoolNLTK#64]

**Comment by happypycode** [comment]
```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fool\__init__.py", line 10, in <module>
    from fool import lexical
  File "C:\ProgramData\Anaconda3\lib\site-packages\fool\lexical.py", line 8, in <module>
    from fool.predictor import Predictor
  File "C:\ProgramData\Anaconda3\lib\site-packages\fool\predictor.py", line 8, in <module>
    from tensorflow.contrib.crf import viterbi_decode
ModuleNotFoundError: No module named 'tensorflow.contrib'
```
之所以这样是因为fool模块支持的tensorflow版本较低。
This is because that the fool module's tensorflow version support is not new.
我的版本是2.2.0rc1。
My version is 2.2.0rc1.

**Comment by happypycode** [comment]
希望能更新！
Hope new version support!
